language: php

matrix:
  fast_finish: true
  include:
    - php: "7.2"
      env: DB=pgsql
    - php: "nightly"
      env: DB=pgsql
    - php: "master"
      env: DB=pgsql
  allow_failures:
    - php: "nightly"
    - php: "master"

services:
  - postgresql

before_install:
  - sudo LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php
  - sudo apt-get -y update
  - sudo apt-get install make build-essential automake php7.2-dev php-pear php7.2-curl libsodium-dev php7.2-sodium

install:
  - composer update
  - echo "[]" > src/config/gears.json
  - echo "[]" > src/config/gadgets.json
  - echo "[]" > src/Cabin/Bridge/config/gadgets.json
  - echo "[]" > src/Cabin/Hull/config/gadgets.json
  - cp src/config/cabins.json.dist src/config/cabins.json
  - cp src/config/databases.json.dist src/config/databases.json
  - cp src/config/universal.json.dist src/config/universal.json
  - chmod 0775 src/config/gears.json
  - chmod 0775 src/config/gadgets.json
  - chmod 0775 src/Cabin/Bridge/config/gadgets.json
  - chmod 0775 src/Cabin/Hull/config/gadgets.json
  - chmod 0775 src/config/cabins.json
  - chmod 0775 src/config/databases.json
  - chmod 0775 src/config/universal.json
  - psql -c 'create database airship_test;' -U postgres
  - chmod +x src/CommandLine/travis-build.sh
  - src/CommandLine/travis-build.sh

script:
  - vendor/bin/phpunit
  - vendor/bin/psalm

